# permissions for end users to edit recipes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: recipe-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: recipe
    app.kubernetes.io/part-of: recipe
    app.kubernetes.io/managed-by: kustomize
  name: recipe-editor-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - recipes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - recipes/status
  verbs:
  - get
